### PR TITLE
Update label.md

### PR DESCRIPTION
**Pull request by Nikhil27b**
### Description
Labels are components used to show text. A label displays text which is specified by the Text property. Other properties, all of which can be set in the Designer or Blocks Editor, control the appearance and placement of the text.

### Screenshots (if appropriate):
screenshot_2018-11-18-15-13-14-02

## Types of changes:
- [x] Correct a spelling
- [x] Add new information
- [x] Change information

## Checklist:
- [x] I have proofread the changes. (Spellings, grammar, etc)
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Nikhil27b** [comment]
Okk thank you

**Comment by Nikhil27b** [comment]
Check i update all the images

**Comment by barreeeiroo** [comment]
All of them are still wrong
You have to use a relative path with images uploaded at our repo, not to Github CDN

**Comment by barreeeiroo** [comment]
Closing this:
1. Merge conflicts
2. Outdated
3. No updates

**Pull request closed without merging**
