### PR TITLE
Update web-viewer.md

### PR DESCRIPTION
**Pull request by Nikhil27bYT**
### Description
You Can be excess the viewer in 4.4 and above android devices and webview provide desktop view , you can be excess the html also in webview and java script also in webview  and from the webview you can be easily excess the any website and  also web viewer have a go back and get catch components   
### Screenshots (if appropriate)

overview webviwer

## Types of changes:
- [x] Correct a spelling
- [x] Add new information
- [x] Change information

## Checklist:
- [x] I have proofread the changes. (Spellings, grammar, etc)
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Sander0542** [comment]
Looks good, but I would love to see images of the block here too

**Comment by Nikhil27bYT** [comment]
Okk I will be adding too

**Comment by Nikhil27bYT** [comment]
And check another pull request for floting action button

**Comment by barreeeiroo** [comment]
Closing this:
1. Merge conflicts
2. Outdated
3. No updates

**Pull request closed without merging**
