### PR TITLE
Update tab-layout.md

### PR DESCRIPTION
**Pull request by ShreyashSaitwal**
## Types of changes:
- [x] Correct a spelling
- [x] Add new information
- [x] Change information

## Checklist:
- [x] I have proofread the changes. (Spellings, grammar, etc)
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by barreeeiroo** [comment]
I see you have linked some images, but I don't see them in the PR. Have you uploaded them?

**Comment by Shreyash193** [comment]
> I see you have linked some images, but I don't see them in the PR. Have you uploaded them?

Oh wait. I uploaded them in the wrong path.

**Comment by Shreyash193** [comment]
Can you check if they are visible now?

**Comment by barreeeiroo** [comment]
No, maybe you forgot to push the changes?

**Comment by Shreyash193** [comment]
Maybe I created a new pull request by mistake. I'm doing everything on my phone.

**Comment by Shreyash193** [comment]
Are they visible now?

**Pull request closed without merging**
