### PR TITLE
Image replacement in Live Development - Wi-Fi / USB

### PR DESCRIPTION
**Pull request by yanquisalexander**
### Description

Replace images with more updated ones (Live Development - Wi-F / USBi)

## Types of changes:
- [ ] Correct a spelling
- [ ] Add new information
- [x] Change information

## Checklist:
- [x] I have proofread the changes. (Spellings, grammar, etc)
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by yanquisalexander** [comment]
Ok, I'm cloning to Local since I can't rename from the web interface

**Comment by yanquisalexander** [comment]
Ready ✅

**Comment by conorshipp** [comment]
Can you also remove the `.PNG` files? They aren't needed now the `.png` files are replacing the old images.

**Comment by yanquisalexander** [comment]
Ready

**Comment by conorshipp** [comment]
Thanks @yanquisalexander!

**Pull request merged**
